fix: addLiquidity token ratio
martriay/scAMM pull request #5
Opened 2022-02-09 21:59 UTC by munozlucas

Buenas, primero que nada muy bueno el curso muchas gracias.

Estoy siguiendo paso por paso lo que vas haciendo pero me llamó la atención la parte de mantener el ratio de token/ether en addliquidity.
Luego de pasar el check de que _tokenAmount >= correctTokenAmount se está  transfiriendo al contrato la cantidad de token que el usuario está enviando a la funcion addLiquidity.
Si no me equivoco esto estaría rompiendo el ratio token/ether en la pool.

Ejemplo: si el usuario envía 20 tokens, pero el correctTokenAmount da 15, lo correcto sería hacer un transfer al contrato de 15 y no de 20, "devolviendo" al usuario los 5 restantes para no romper con el ratio.

Saludos.

2022-02-09 22:34 UTC, munozlucas commented
Pongo con un ejemplo 3 llamadas a addLiquidity:

1) envío 1 token y 1 ether 
 En este caso no habría problema ya que no hay ninguna restricción.

2) Desposito 1 ether, y 10000 tokens.
En este caso podría hacerlo ya que correctTokenAmount = 1 * 1 / 1 = 1 token

3) si deposito 1 ether:
 correctTokenAmount = 1 * 10001 / 2 = 5000,5 tokens.
Necesitaría depositar 5000,5 tokens en este tercer paso para la contraparte de 1 ether


Conclusión, la relación de tokens con respecto a ether que necesito ingresar  siempre va a ir creciendo, por el hecho de que en cada llamado estoy depositando un ratio mayor de tokens.
Entonces va a llegar un punto que voy a necesitar demasiados tokens para una cantidad x de ether ya que la relación siempre va a decrecer y nunca decrecer.

Encontré una implementación parecida de addLiquidity: https://medium.com/coinmonks/programming-defi-uniswap-part-2-13a6428bf892

Saludos!

2022-02-09 23:21 UTC, munozlucas commented
Siguiendo con mi investigación, fui al repo de uniswap v2: https://github.com/Uniswap/v2-periphery/blob/master/contracts/UniswapV2Router02.sol

La función addLiquidity recibe 2 tokens. y devuelve el 100% para uno de los 2 tokens y para el otro devuelve el optimo que no es mas que hacer la misma cuenta que se hace en el correctTolenAmount.

  // given some amount of an asset and pair reserves, returns an equivalent amount of the other asset
    function quote(uint amountA, uint reserveA, uint reserveB) internal pure returns (uint amountB) {
        require(amountA > 0, 'UniswapV2Library: INSUFFICIENT_AMOUNT');
        require(reserveA > 0 && reserveB > 0, 'UniswapV2Library: INSUFFICIENT_LIQUIDITY');
        amountB = amountA.mul(reserveB) / reserveA;
    }

amountB luego se convierte en amountBOptimal que sería lo mismo que correctTolenAmount

2022-02-16 14:11 UTC, eugenioclrc requested changes

2022-02-16 14:11 UTC, eugenioclrc commented on contracts/Exchange.sol
> +        token.transferFrom(msg.sender, address(this), tokenAmount);
@munozlucas Confirmo que el bug existe, pero no es enviando ether.

En el caso puntual de tu commit, `tokenAmount` no esta difinido... ya que la primera vez `(getReserve() == 0)`, por lo que nunca entra en el if. 

Por otro lado,el caso que propones es depositar ETH para modificar el balance, no lo veo posible por que no existe fallback o receive function para recibir el ether, este es el test case que propones;
```
envío 1 token y 1 ether
En este caso no habría problema ya que no hay ninguna restricción.

Desposito 1 ether, y 10000 tokens.
En este caso podría hacerlo ya que correctTokenAmount = 1 * 1 / 1 = 1 token

si deposito 1 ether:
correctTokenAmount = 1 * 10001 / 2 = 5000,5 tokens.
Necesitaría depositar 5000,5 tokens en este tercer paso para la contraparte de 1 ether
```
El test case es valido, pero es imposible depositar en el exchange por no existir los fallback;
https://solidity-by-example.org/sending-ether/

Tambien chequeate este test;
https://github.com/eugenioclrc/scAMM/blob/90b63122aec6c214161ea2ec18d5803d5a730eb1/test/liquidity.test.js#L75

En si se puede romper enviando FTH, podes usar este test para validar tu caso;
https://github.com/eugenioclrc/scAMM/blob/90b63122aec6c214161ea2ec18d5803d5a730eb1/test/liquidity.test.js#L84

2022-02-19 16:51 UTC, eugenioclrc commented on contracts/Exchange.sol
> +        token.transferFrom(msg.sender, address(this), tokenAmount);
@jm42 te tiro un ping por que estas activo... que opinas vos al respecto de este issue?

2022-02-19 18:22 UTC, jm42 commented on contracts/Exchange.sol
> +        token.transferFrom(msg.sender, address(this), tokenAmount);
Es cierto que no se puede enviar ether directamente a la pool por no tener definido el receive o fallback, por lo cual el ¨desbalanceo¨ no podría darse que haya mas ETH que tokens. El problema entonces parece que radica cuando se envían mas tokens de los necesarios, en donde `_tokenAmount > tokenAmount`, en donde al transferirse los ¨deseados¨ quedarian mas tokens que ETH.

La solcuión bien está en ese caso en transferir la cantidad necesaria (`tokenAmount`) y no la cantidad enviada en los argumentos (`_tokenAmount`). Claramente este cambio no puede funcionar así como está por el tema que `tokenAmount` solo esta definido dentro un condicional.

2022-02-19 18:32 UTC, eugenioclrc commented on contracts/Exchange.sol
> +        token.transferFrom(msg.sender, address(this), tokenAmount);
El token ratio siempre que alguien lo use para comprar o vender esta cambiando.

Si metes mas tokens que balance de eth no pasa nada, solo hace que el token valga menos y que al agregar liquidez tengas que meter liquidez en el ratio que este en el momento.

2022-02-19 20:25 UTC, jm42 commented on contracts/Exchange.sol
> +        token.transferFrom(msg.sender, address(this), tokenAmount);
Si vale menos salís perdiendo si no le pasas `_tokenAmount = tokenAmount`, ya que si pasas menos te van a dar misma `liquidity` que si enviaras justo, el resto (`tokenAmount - _tokenAmount`) lo estarías perdiendo.

Yo pensé lo siguiente: Dado que se agrega liquidez con relación 1 a 1: 100 eth y 100 tokens por ejemplo donde se mintearia 100 LP. Luego agregas liquidez con 1 eth y 100 tokens, entonces `_tokenAmount = 100` y `tokenAmount = 1` ya que mantiene la relación con el balance de eth. Se te mintearian un solo LP, pero aún se te transferirían los 100 tokens, a lo que los balances quedarían en 101 eth y 200 tokens.

Si entiendo bien, primero los LP valdrían 1 eth y 1 token, pero después pasarían a valer 1.01 eth y 0.5 tokens. Con ese solo LP que te dieron, no llegas a sacar lo que pusiste ya que se diluyó entre todos.

Otra solución es cambiar el require a igual estricto en vez de mayor igual.

2022-02-19 20:56 UTC, jm42 commented on contracts/Exchange.sol
> +        token.transferFrom(msg.sender, address(this), tokenAmount);
Hice un test para entenderlo mejor.

```js
    it.only("fuck liquidity", async () => {
      const uno = ethers.utils.parseEther("1")
      const cien = ethers.utils.parseEther("100")

      await token.approve(exchange.address, ethers.constants.MaxUint256)

      await expect(
        await exchange.addLiquidity(cien, { value: cien })
      )
      .to.emit(exchange, "AddLiquidity").withArgs(deployer.address, cien, cien)
      .to.emit(token, "Transfer").withArgs(deployer.address, exchange.address, cien)

      await expect(
        await exchange.addLiquidity(cien, { value: uno })
      )

      // esto es lo que esperamos que pase actualmente
      .to.emit(exchange, "AddLiquidity").withArgs(deployer.address, uno, cien)
      .to.emit(token, "Transfer").withArgs(deployer.address, exchange.address, cien)

      // esto es lo que deberia pasar
      // .to.emit(exchange, "AddLiquidity").withArgs(deployer.address, uno, uno)
      // .to.emit(token, "Transfer").withArgs(deployer.address, exchange.address, uno)

      await expect(
        await exchange.removeLiquidity(uno)
      )

      // aca falla, esperariamos que nos devuelva lo nuestro
      .to.emit(exchange, "RemoveLiquidity").withArgs(deployer.address, uno, cien)
      .to.emit(token, "Transfer").withArgs(exchange.address, deployer.address, cien)

      // una vez que esta el fix deberia devolver esto
      // .to.emit(exchange, "RemoveLiquidity").withArgs(deployer.address, uno, uno)
      .to.emit(token, "Transfer").withArgs(exchange.address, deployer.address, uno)
    });
```

cc @munozlucas @eugenioclrc

2022-10-28 19:54 UTC, closed without merging